name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: docker/setup-buildx-action@v3.3.0
      - run: docker buildx build .

