name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: docker/setup-buildx-action@v2.10.0
      - run: docker buildx build .

