name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: docker/setup-buildx-action@v1.7.0
      - run: docker buildx build .

